# -*- mode: shell-script; sh-shell: bash-*-
# ~/.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# pyenv stuff
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Don't do the annoying byte code
export PYTHONDONTWRITEBYTECODE="true"

acolytegm ()
{
    cd ~/dev/acolytegm   
}
