# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/lamberss/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

alias e='emacs -nw'
alias ls='ls --color=auto'

. /usr/lib/python3.5/site-packages/powerline/bindings/zsh/powerline.zsh

